version: '3'
services:
  client:
    build: .
    command: python client.py
    volumes:
      - ./common:/usr/app/common/
      - ./client:/usr/app/
  server:
    build: .
    command: python server.py
    volumes:
      - ./common:/usr/app/common/
      - ./server:/usr/app/
