version: '3'
services:
  client:
    build: .
    command: python client.py
    volumes:
      - ./client:/usr/app/
    depends_on:
      - server
  server:
    build: .
    command: python server.py
    volumes:
      - ./server:/usr/app/
    expose:
      - 5002
